import Head from 'next/head';
import { useRef, useState } from 'react';
import { useOnceEffect } from '@reactuses/core';
import '@blocksuite/presets/themes/affine.css';

export default function Index() {
  const [loading, setLoading] = useState(true);
  const ref = useRef<HTMLDivElement>(null);

  useOnceEffect(() => {
    (async () => {
      const { createEmptyPage, DocEditor } = await import(
        '@blocksuite/presets'
      );
      const page = createEmptyPage().init();
      const editor = new DocEditor();
      editor.page = page;
      setLoading(false);
      ref.current?.append(editor);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Blocksuite + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading && <span>Loading</span>}
      <div id="app" ref={ref}></div>
    </>
  );
}
