name: Daily CI

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  daily-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build esbuild
        run: |
          cd packages/esbuild
          pnpm run build
          pnpm serve
      - name: Run esbuild tests
        run: |
          cd packages/esbuild
          pnpm test

      - name: Build next
        run: |
          cd packages/next
          pnpm run build
          pnpm start
      - name: Run next tests
        run: |
          cd packages/next
          pnpm test

      - name: Build nuxt
        run: |
          cd packages/nuxt
          pnpm run build
          pnpm preview
      - name: Run nuxt tests
        run: |
          cd packages/nuxt
          pnpm test

      - name: Build rspack
        run: |
          cd packages/rspack
          pnpm run build
          pnpm serve
      - name: Run rspack tests
        run: |
          cd packages/rspack
          pnpm test

      - name: Build webpack
        run: |
          cd packages/webpack
          pnpm run build
          pnpm serve
      - name: Run webpack tests
        run: |
          cd packages/webpack
          pnpm test
