name: Daily CI

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  daily-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: pnpm install

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: Build and Test esbuild
        run: |
          cd packages/esbuild
          pnpm run build
          pnpm test

      - name: Build and Test next
        run: |
          cd packages/next
          pnpm run build
          pnpm test

      - name: Build and Test nuxt
        run: |
          cd packages/nuxt
          pnpm run build
          pnpm test

      - name: Build and Test webpack
        run: |
          cd packages/webpack
          pnpm run build
          pnpm test

      - name: Build and Test rspack
        run: |
          cd packages/rspack
          pnpm run build
          pnpm test

      - name: Build and Test angular
        run: |
          cd packages/angular
          pnpm run build
          pnpm test
